### PR TITLE
Disable failing routes and cronjobs. part of #445

### PR DESCRIPTION
**Pull request by fcaps**
All routes for clan and leaderboard are disabled with a new 503 view:
The links are still there, but will lead to this page.
image

### CODE REVIEW

**Comment by Sheikah45** [comment]
I think your branch has stray commits. We squash and merge so you have a few commits from the last PR I believe that can be removed.

**Comment by fcaps** [comment]
> I think your branch has stray commits. We squash and merge so you have a few commits from the last PR I believe that can be removed.

updated

**Comment by Sheikah45** [comment]
It still is showing the extraneous commits because you just merged the remote branch in. It will probably be better if you rebase your branch and drop the duplicate commits

**Comment by fcaps** [comment]
yeah, long time ago since i worked with squash commits.
now it's good

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
