### PR TITLE
Feature/check if user taken

### PR DESCRIPTION
**Pull request by 1-alex98**

### CODE REVIEW

**Comment by 1-alex98** [comment]
Don't worry the library has some sort of built in delay a quick typing user is not gonna trigger 20 requests tested that

**Comment by 1-alex98** [comment]
Only once the user starts typing it files a request

**Comment by 1-alex98** [comment]
Fixes #191

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
Breaks on the test server with internal server error when navigating to the register page:

```
Error: /code/templates/mixins/form/account.pug:15:15

input is a self closing element: <input/> but contains nested content.
    at makeError (/code/node_modules/pug-error/index.js:32:13)
    at Compiler.error (/code/node_modules/pug-code-gen/index.js:92:15)
    at Compiler.visitTag (/code/node_modules/pug-code-gen/index.js:560:14)
    at Compiler.visitNode (/code/node_modules/pug-code-gen/index.js:308:37)
    at Compiler.visit (/code/node_modules/pug-code-gen/index.js:297:10)
    at Compiler.visitBlock (/code/node_modules/pug-code-gen/index.js:380:12)
    at Compiler.visitNode (/code/node_modules/pug-code-gen/index.js:308:37)
    at Compiler.visit (/code/node_modules/pug-code-gen/index.js:297:10)
    at Compiler.visitTag (/code/node_modules/pug-code-gen/index.js:569:12)
    at Compiler.visitNode (/code/node_modules/pug-code-gen/index.js:308:37)
```

**Comment by 1-alex98** [comment]
oh yeah Webstorm changed indent when pushing ... lol, lemme fix the indent

**Comment by 1-alex98** [comment]
Built a new RC for u https://github.com/FAForever/website/releases/tag/v1.7.10-RC2

**Review by Brutus5000 — APPROVED** [review]
I love it

**Pull request merged**
