### PR TITLE
Registration page: steam linking mandatory warning

### PR DESCRIPTION
**Pull request by Geosearchef**

### CODE REVIEW

**Comment by 1-alex98** [comment]
Should we not redirect the user to link steam when he registers?

**Comment by Geosearchef** [comment]
This would have to happen on clicking the link in the email, isn't this call just directed to the API? Also forwarding the user to the steam link page won't work as the user will have to login on the website first.

**Comment by 1-alex98** [comment]
Hmm yeah, maybe that could be a future thing tho. Because I imagine people will still miss to steam link

**Comment by micheljung** [comment]
I assume most users won't read this but at least we can say "it was there" ;)

**Pull request merged**
