### PR TITLE
Change text and table header formatting.

### PR DESCRIPTION
**Pull request by germanicianus**
This change makes the client download page non-discriminating.

### CODE REVIEW

**Comment by germanicianus** [comment]
The client download page text should be ok, but please double-check the formatting.

**Comment by 1-alex98** [comment]
Can you provide an image?

**Comment by germanicianus** [comment]
New text and formatting (updated):
faforever_client_download_page_new

**Comment by Brutus5000** [comment]
The feature comparison table linked is by no means official. This topic is still highly subjective.

**Comment by germanicianus** [comment]
Yes, regarding the linked page it is (the link was already there before), but at least the user isn’t influenced heavily in favour of one client when having his first glance at the page but really needs to have a look at both clients. That we have no „official“ feature list/comparison for the clients is another topic. If desired, I can remove the link to the wiki page, but how should a new user then decide which client to use - by trying them both?

**Review by micheljung — APPROVED** [review]

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
