### PR TITLE
Grunt refactor

### PR DESCRIPTION
**Pull request by Raistlfiren**
Split styles into separate sass files for each page
Set grunt to compile the sass
Remove page specific imports from site.scss
Add page specific css imports to views
Updated README.

### CODE REVIEW

**Comment by Blodir** [comment]
Sass doesn't seem to be compiling with these changes

**Comment by Raistlfiren** [comment]
Hmmm... I just did a fresh install of my fork and checked out the branch. It seemed to work just fine. Although, grunt doesn't automatically compile these changes at first. I added the following step to the README before grunt serve, grunt sass:dev. Try that, and see if that fixes your issue.

Thanks!

**Comment by Blodir** [comment]
I had to manually `npm install grunt-contrib-sass` and `gem install compass` before I could `grunt sass:dev`
Running on a windows machine, maybe that should be added to readme

**Comment by Raistlfiren** [comment]
Hmmm... The `grunt-contrib-sass` file should already be included in the package.json when you did `npm install`. I forgot about that step, and I had to do the same thing. Sorry about that. I am including it in the README now.

**Pull request merged**
