### PR TITLE
Add New Style Choices

### PR DESCRIPTION
**Pull request by MrRowey**

### CODE REVIEW

**Comment by Brutus5000** [comment]
Care to explain what you actually changed?

**Comment by MrRowey** [comment]
xD that would be helpful

This is to add 3 New styles to allows us to use the badge feature and make it easier to see what different content there is
current additions to the styles are
- Twitch
- Youtube
- Tournaments

**Comment by Brutus5000** [comment]
A screenshot would be nice. I have no clue what the badge feature is supposed to be

**Comment by MrRowey** [comment]
I've circled the area on the news post that is called the Badge.

The changes will give us access to different styles when we add badges.

so we will now have cases to the following:

Golden for Hero Posts ( Already available)
Red for I'mportaint posts
Green for youtube videos
Purple for twitch

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
