### PR TITLE
Adding Open-Source License 

### PR DESCRIPTION
**Pull request by MrRowey**
This is a Draft Pull Request to add an Open-Source License to the FAF Website so we can add 3rd party software to the repo to help with localization support for the website in multiple languages. Since the website was set up on GitHub there was no License set which stops us from being able to apply for Open-Source licenses from other companies.

To be able to add this MIT License to the Website I need approval from all Contributors to the website. This may take some time and the first person who says no to this PR then were unable to add a license to this repository.

All I need is for you to comment on this draft saying that you are okay with this License.

- [x] @Raistlfiren
- [x] @Blodir 
- [x] @Brutus5000 
- [x] @Sheeo 
- [x] @MrRowey 
- [x] @1-alex98 
- [x] @Rackover 
- [x] @FtXCommando 
- [ ] @lextoc 
- [ ] @duk3luk3 
- [x] @Sheikah45 
- [x] @Geosearchef 
- [x] @micheljung 
- [x] @dmitrii-badretdinov 
- [x] @Kazbek 
- [x] @Syldarion 
- [x] @JeroenDeDauw 
- [x] @norraxx 
- [x] @domis4 
- [x] @p4block 
- [x] @Viba 
- [x] @speed2CZ 
- [ ] @germanicianus 
- [ ] @EcoNooob 
- [x] @shalkya 
- [x] @IDragonfire 
- [ ] @jordan-schnur 
- [x] @anihilnine 
- [x] @Gatsik 
- [x] @NapMorax 
- [ ] @FlyingThunder 
- [x] @Askaholic 
- [ ] @VoRGoR

### CODE REVIEW

**Comment by Kazbek** [comment]
Im ok

**Comment by Sheikah45** [comment]
Fine by me

**Comment by JeroenDeDauw** [comment]
+1

**Comment by Askaholic** [comment]
+1. Good luck!

**Comment by dmitrii-badretdinov** [comment]
I contributed code to FAF? It was an honor, gentlemen. 
You have my full approval to do whatever you want with the code I contributed.

**Comment by MrRowey** [comment]
> I contributed code to FAF? It was an honor, gentlemen. You have my full approval to do whatever you want with the code I contributed.

apparently you did the TOS and Privacy in Russian not that they were ever displayed afaik

**Comment by dmitrii-badretdinov** [comment]
> apparently you did the TOS and Privacy in Russian not that they were ever displayed afaik

Meanwhile I've been trying to find what exactly I did in my activity archives. Thank you :D 
Now I remember I indeed wrote the translation for that.

**Comment by Geosearchef** [comment]
Am I ok with my nearly non existent contributions to the website becoming free prey for everyone to use for their own malicious intents and purposes? Definetly!

**Comment by Brutus5000** [comment]
Works for me.

**Comment by speed2CZ** [comment]
yes

**Comment by norraxx** [comment]
👍

**Comment by Syldarion** [comment]
+1

**Comment by p4block** [comment]
[WTFPL](http://www.wtfpl.net/) should be the default license, but here we are. Yes, ofc.

**Comment by MrRowey** [comment]
I've never heard of that licence before will give it a read for future notes

**Comment by Viba** [comment]
👍

**Comment by shalkya** [comment]
sure

**Comment by micheljung** [comment]
yes

**Comment by 1-alex98** [comment]
sure

**Comment by Blodir** [comment]
approved!

**Comment by IDragonfire** [comment]
+1. Good luck!

**Comment by NapMorax** [comment]
You have my approval given the 2 lines of code I update to do ladder league!

**Comment by Raistlfiren** [comment]
Sure thing, boss.  :)

**Comment by Gatsik** [comment]
SeemsGood

**Comment by anihilnine** [comment]
ok

**Comment by Sheeo** [comment]
👍

**Comment by Rackover** [comment]
Hello,

I definitely think adding a license to this code is good measure, but why not GPLv3 like Server ?
Not that I think our website is _that_ unique or valuable, but MIT allows someone to edit the source & close it, or even sell it, just by crediting us. I would prefer this repository, like other repositories, to use the GPLv3 license instead to guarantee full and permanent source openness forever 🙂

What is your opinion on this?

**Comment by Brutus5000** [comment]
We discussed it with 2 insights: GPL is useless for "cloud" services. It only applies if you distribute the application (a binary). For this case there is the AGPL.

Nevertheless for many cases and new apps we went with MIT as some of us developers want to be allowed to copy & paste this code for our daily jobs. This is (at least for me) a two way street.
Looking at the java-api for example: I copied a lot of code from there for a project and all the (other) issues I encountered and resolved can be applied to FAF too (or some bugs I fixed in upstream libraries such as Elide).

**Comment by Rackover** [comment]
Ok, I would have preferred AGPL & make derogations to developers by personal request, but I will agree to MIT for the sake of progress 🚀

**Comment by MrRowey** [comment]
> to

Thanks :)

**Comment by MrRowey** [comment]
image

Proxy Aggrement from FTX

**Comment by Askaholic** [comment]
> image
> 
> Proxy Aggrement from FTX

Doesn’t say what he’s agreeing to

**Comment by MrRowey** [comment]
> 

image

@Askaholic  better ?

**Comment by domis4** [comment]
im fine with it 👍

**Comment by micheljung** [comment]
who closed this w/o comment and why?

**Comment by Sheikah45** [comment]
I am guessing it was closed because the license was added here 0db040c3e587c24519c5b04acbf0550f8884d4a5

**Comment by Brutus5000** [comment]
Rowey messed up his fork and the branch was deleted.

**Pull request closed without merging**
