### PR TITLE
Added a fix for the bad image downscaling

### PR DESCRIPTION
**Pull request by phongu**
Attempt at fixing the low quality image downscaling on the newshub using some canvas elements that sit inside the image divs and a purpose-built library: https://github.com/nodeca/pica

### CODE REVIEW

**Comment by phongu** [comment]
Fixed the CORS issue, with help from Brutus

**Review by JaviTrek — COMMENTED** [review]
The changes seem to not affect the current newshub in any negative way. Have you tested this changes in a local version of the FAF client @phongu ? If so, I'll Approve it/give the approving review. Thanks for your work!

**Comment by phongu** [comment]
Javi yes i tested on the faf client and it works.

**Review by JaviTrek — APPROVED** [review]
I have just tested this locally inside the FAF client. All seems to be working correctly.
image


### On a separate note
Approving these changes will also bring my PR from like a month (or two?) ago where I fixed the client sometimes opening links inside the client instead of a new tab in the browser.

**Pull request merged**
