### PR TITLE
Add an Email Address Issues Notice

### PR DESCRIPTION
**Pull request by MrRowey**
Adds a Clear statement about Microsoft emails & the ongoing issues with Gmail issues

### CODE REVIEW

**Comment by MrRowey** [comment]
@Brutus5000 are you able to push this change and Deploy it ?

**Comment by magge-faf** [comment]
You did a good pre-work on the text, however it has a few mistakes - Please use this corrected text, or better just use the last one:


**Corrected text:**

---

Please be aware that Microsoft email address that use `@hotmail, @live, @outlook` etc., do not work, as Microsoft blocks FAF from sending any outgoing emails. Activation and password resets will not work.

Google has been rate limiting FAF service, you may not be able to register/password reset with `@gmail` and `@googlemail`.

There is currently nothing we can do about it, except to wait.

---


**Preferred version:** - Make it short, snappy and understandable even for English beginners. There is no need to write any explanation whatsoever. It will just confuse people.

---

The following email addresses are not working:
`
@hotmail, @live, @outlook, @googlemail, @gmail`

Use any other provider.

---

Edit: Even better, if people enter those addresses in the registration site, they see a red warning text, that the email is not working/allowed, and they need to take another provider.

The gmail problem is recurring every few days and is annoying to deal with, when people ask (rightly TBH) in Discord/Forum/PM what the deal about that is. If it does not work consistently, then block it, otherwise it will just cost time and creates a bad experience for players who expect that it works.

Edit2: And if anyone asks for an official statement/explanation, then we can post something in the Forum as pinned thread.

**Comment by MrRowey** [comment]
@magge-faf you could just fork the website repo and just make the changes to this pr yourself

**Comment by JaviTrek** [comment]
Someone needs to put a flash message into the website so that all this PR's adding HTML stop lol. Doesnt the current website feature flash messages?

**Comment by MrRowey** [comment]
> Someone needs to put a flash message into the website so that all this PR's adding HTML stop lol. Doesn't the current website feature flash messages?

this is something we need to say not just pop up when creating and account as it need to be visible before the user creates the account

**Comment by MrRowey** [comment]
@magge-faf better ?

**Comment by magge-faf** [comment]
Yes, good job, and thanks for the fork idea - I will do it as soon I am home at my dev-machine, so I am prepared for the next time.

I will write some nice PR thread under the FAQ section in the next days why FAF is having such problems, so we can point to it, when people are asking in Aeolus, Discord, etc. what is going on with this email stuff.

**Pull request closed without merging**
