### PR TITLE
Update leagues.json

### PR DESCRIPTION
**Pull request by FtXCommando**

### CODE REVIEW

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
We really need to build something so this is does not require a new website release

**Comment by Brutus5000** [comment]
We really need to get rid of this, as it makes the api query like 100k players and rating with SINGLE queries.

**Comment by 1-alex98** [comment]
oh yeah that as well

**Comment by 1-alex98** [comment]
Rather 10k players and their games right

**Comment by Brutus5000** [comment]
I just saw an endless log stream on test (hibernate sql log is active there)

**Pull request merged**
