### PR TITLE
Updates

### LINKED ISSUE #21: Player rating over time graph/statistics
Replacement for the rating over time popup that the client used to have. Once implemented we'll need to webview/link in the players list in client

### LINKED ISSUE #77: Cron job not working properly...

### LINKED ISSUE #114: Use alpine node image
Those are generally a lot slimmer, and we have enough bloated images already

### LINKED ISSUE #116: Fix donation link
The donation link still points to visionik's paypal.
Replace it with a link to our Patreon account: https://www.patreon.com/faf

The icon should be replaced as well.

### LINKED ISSUE #120: Repair reCAPTCHA registration form
https://www.google.com/recaptcha/intro/android.html

### PR DESCRIPTION
**Pull request by Raistlfiren**
- Updated to Font Awesome 5. Fixed links from Youtube to Patreon.
- Added recaptcha to registration form
- Added a new blurb to the bottom of the homepage with a list of the top five players
- Converted to node alpine image
- Converted cron jobs to node timers.

Closes #116 
Closes #120 
Closes #21 
Close #114 
Close #77

### CODE REVIEW

**Comment by Sheeo** [comment]
The dockerfile needs a rebase; otherwise the changes look good

**Review by Sheeo — CHANGES_REQUESTED** [review]
See above.

**Comment by 1-alex98** [comment]
We should really get the branch up to date and apply it. Updating donation Link is outstanding pretty long now.

**Comment by Sheeo** [comment]
Merged as of at least: https://github.com/FAForever/website/commit/77ebbb15c690e9192a456a74a9d722d3cdcfcb4b

**Pull request closed without merging**
