### PR TITLE
Clean up frontend, install autoprefixer, restyle footer

### PR DESCRIPTION
**Pull request by lextoc**
I've cleaned (mostly) the stylesheets and used 2 spaces instead of tabs everywhere. Convert (almost) all SCSS files to SASS files. Reorganised the stylesheets and installed autoprefixer. Restyled the footer and removed the margin-bottom's on the `#body`, also added `.content` to this tag and used that for styling (might still be some styling left on `#body` ...)

### CODE REVIEW

**Comment by IDragonfire** [comment]
Suggestion: After merging this the css part, icons, font should be moved to a seperated `general webapp` repo and imported as git submodule. Then other apps, e.g. the clanapp can also import the `general webapp` repo and have the same style!

**Comment by lextoc** [comment]
A small thing to note: the two donate buttons in the footer have been replaced with a link to the contributions page. I did this keeping in mind (and discussed on Slack) that we'll have some sort of donate button in the navigation (after I restyled it) or fixed on every page.

**Comment by Cheyans** [comment]
Can you include screenshots?

**Comment by lextoc** [comment]
@Cheyans They are on Slack. FYI you can clone pull requests (locally) to check them out.

**Comment by IDragonfire** [comment]
https://faforever.slack.com/archives/website/p1484401262004042

**Comment by lextoc** [comment]
Here's a screenshot of the desktop version: https://cl.ly/0S1Y2A3K011R

**Comment by Raistlfiren** [comment]
Thanks lextoc! 👍 I appreciate the PR.

Please review the following tasks:

- [ ] Figure out why `grunt serve` and `node express.js` takes forever to load local website
 - This could be because individual pages are trying to load a CSS file and it isn't there anymore...
- [ ] Integrate donate back into navigation or footer
- [ ] If all CSS is in one file now, then modify and remove the individual CSS includes for each page
- [ ] Checkout the tournaments, 1v1, global, and calendar page for style changes that look incorrect.
 - The titles of tables are lighter

Thanks!

**Comment by duk3luk3** [comment]
There shouldn't be a merge commit in a PR.

**Comment by Cheyans** [comment]
@lextoc, you can resolve that via `git pull --rebase <remote> <branch>`

**Comment by IDragonfire** [comment]
@lextoc What is the general state of the PR?

**Comment by Cheyans** [comment]
https://faforever.slack.com/archives/website/p1485375640005083

**Comment by lextoc** [comment]
I committed the last changes to the navigation and footer, it should be ready to merge now. I did not have the chance to check the user dropdown while logged in as I couldn't log in locally (might have forgotten my password, but I think it didn't work ...).

I've tested the new navigation on all main browsers and my Nexus 5 / iPad Mini. Added headroom.js for extra breathing space.

All issues @Raistlfiren mentioned should be fixed as well. Someone should probably test everything real quick before accepting the PR but I don't think I missed anything.

**Comment by lextoc** [comment]
Screenshots:
navigation on desktop: https://cl.ly/382O3C0I0k2X
footer on desktop: https://cl.ly/2Y3N2S3G0V0N
closed nav mobile: https://cl.ly/0w263j463g41
opened nav mobile: https://cl.ly/2540201a3X1n
footer mobile: https://cl.ly/0S1Y3o3J410Q

**Comment by IDragonfire** [comment]
I only dislike that the width (alignment) is not the same here:
image

**Pull request closed without merging**
