### PR TITLE
Gog linking

### LINKED ISSUE #257: Support GOG License Checking
As per the following thread on the FAF forum:
[https://forum.faforever.com/topic/281/i-bought-forged-alliance-but-not-on-steam-can-i-still-play-on-faf](https://forum.faforever.com/topic/281/i-bought-forged-alliance-but-not-on-steam-can-i-still-play-on-faf)

It would be nice if copies of Supreme Commander Forged Alliance purchased via GOG are also supported by FAF.
It looks like this should already be facilitated by their existing APIs.

What is the current status of the contact with GOG regarding license checking?
I would like to contribute to the implementation of the integration with GOG.

### PR DESCRIPTION
**Pull request by Geosearchef**
fully functional, still need to do some reworking

### CODE REVIEW

**Comment by Brutus5000** [comment]
@Geosearchef Any progress?

**Comment by MrRowey** [comment]
What's the status of this ?

**Comment by Sheikah45** [comment]
Partially started but geosearchef has been afk. I am working on the user_service which will have gog linking though

**Review by MrRowey — APPROVED** [review]
The Linking works and has been verifyed

**Pull request merged**
