### PR TITLE
Latest client download fix

### PR DESCRIPTION
**Pull request by Raistlfiren**
Fixes issue https://github.com/FAForever/website/issues/40

### CODE REVIEW

**Comment by Sheeo** [comment]
I don't think using an environment variable to store the latest download link is a good idea. This means we need to restart the service every time we change the link?

**Comment by Sheeo** [comment]
As for a better solution--I'm not sure. The database has the latest link within it, but we don't currently have database access from this webservice -- I don't see why not though?

**Comment by Raistlfiren** [comment]
Yeah, I was thinking the same thing @Sheeo. We could just pull it from the database, or I could create a new API endpoint. I think the API endpoint is the best way imho, then we can use it other clients easily.

Maybe I can create that endpoint and another endpoint for creating an account.

**Comment by Sheeo** [comment]
Up to you, I don't mind either way. You should coordinate with @Brutus5000 about account creation.

Unfortunately the PHP-code currently backing the account creation isn't published, you'll have to get in touch with @micheljung to get at it.

**Comment by Raistlfiren** [comment]
@Sheeo I updated this PR to include a static link provided by downlord. This should work the best I hope.

**Comment by Sheeo** [comment]
Static links will cause http cache issues (We've had these in the past, so I'd rather not go back to doing that)

An easy alternative is to use this: https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by Raistlfiren** [comment]
Okay rebased and included a cron job to pull the latest link information from the github api every hour.

**Pull request merged**
