### PR TITLE
Add hint to register retail SC/SC:FA key on Steam for Gold edition.

### PR DESCRIPTION
**Pull request by germanicianus**

### CODE REVIEW

**Comment by Brutus5000** [comment]
What's a gold edition? How do I know whether I have one?
Why no just saying: "If you own a retail copy, you can try to activate it on steam. Unfortunately not all retail copies are working on steam" or something like that.

**Comment by germanicianus** [comment]
Register SC **or** SC:FA retail key on Steam -> Get SC Gold Edition (SC **and** SC:FA) on Steam: https://store.steampowered.com/sub/11732/
So maybe my wording is bad. What is your suggestion on wording the above?

**Comment by germanicianus** [comment]
The current wording and formatting/linking is:
>According to [GPG’s statement](https://web.archive.org/web/20140903143132/http://forums.gaspowered.com/viewtopic.php?f=67&t=57459), "ALL existing CD keys for both SC and FA [can be registered] into updated SC:Gold Editions on Steam."

**Comment by Brutus5000** [comment]
Yes, but that is not helping the user the slightest if he still can't link it...

**Pull request merged**
